import { Bot, Context, InlineKeyboard, Keyboard } from "grammy";
import { prisma } from "../lib/db";
import { clock, dateInZone, studioDateTime } from "../lib/time";
import { money, settings } from "../lib/settings";
import { availableSlots, createBooking, SlotTakenError } from "../services/availability";

type OwnerCheck = (ctx: Context) => boolean;
type AdminFlow = Record<string, string>;
const ACTIVE = ["PENDING", "CONFIRMED"] as const;
const status = (value: string) => ({ PENDING: "🟡 Ожидает", CONFIRMED: "🟢 Подтверждена", CANCELLED: "🔴 Отменена", COMPLETED: "⚪ Завершена", NO_SHOW: "⚫ Не пришёл" }[value] ?? value);
const today = async () => dateInZone(new Date(), (await settings()).timezone);
const day = (date: string, offset: number) => { const d = new Date(`${date}T12:00:00Z`); d.setUTCDate(d.getUTCDate() + offset); return d.toISOString().slice(0, 10); };
const dateLabel = (date: string) => new Intl.DateTimeFormat("ru-RU", { day: "numeric", month: "long", timeZone: "UTC" }).format(new Date(`${date}T12:00:00Z`));
const back = () => new InlineKeyboard().text("⬅️ Назад", "ad:menu").text("🏠 Главное меню", "ad:home");

async function flow(userId: string) { const value = await prisma.botFlow.findUnique({ where: { userId } }); return value?.state.startsWith("admin:") ? (value.payload as AdminFlow) : null; }
async function setFlow(userId: string, state: string, payload: AdminFlow = {}) { await prisma.botFlow.upsert({ where: { userId }, update: { state: `admin:${state}`, payload }, create: { userId, state: `admin:${state}`, payload } }); }
async function clearFlow(userId: string) { await prisma.botFlow.deleteMany({ where: { userId } }); }
function adminKeyboard() { return new Keyboard().text("📅 Расписание").text("📋 Записи").row().text("➕ Добавить запись").text("👥 Клиенты").row().text("🐶 Питомцы").text("✂️ Услуги").row().text("💰 Цены").text("👩 Мастера").row().text("🚫 Заблокированные окна").text("📊 Статистика").row().text("⚙️ Настройки").row().text("⬅️ В клиентское меню").resized(); }
async function panel(ctx: Context) { await ctx.reply("⚙️ АДМИН-ПАНЕЛЬ\n\nУправляйте студией кнопками ниже.", { reply_markup: adminKeyboard() }); }
async function masterPicker(ctx: Context, prefix: string) { const masters = await prisma.master.findMany({ where: { isArchived: false }, orderBy: { name: "asc" } }); const kb = new InlineKeyboard(); masters.forEach(m => kb.text(`${m.isActive ? "👩" : "⚪"} ${m.name}`, `${prefix}:${m.id}`).row()); kb.text("⬅️ Назад", "ad:menu"); await ctx.reply(masters.length ? "Выберите мастера:" : "Мастеров пока нет. Добавьте мастера в разделе «👩 Мастера».", { reply_markup: kb }); }
async function datePicker(ctx: Context, prefix: string) { const base = await today(), kb = new InlineKeyboard(); for (let i = 0; i < 14; i++) { const d = day(base, i); kb.text(dateLabel(d), `${prefix}:${d}`); if (i % 2) kb.row(); } kb.row().text("⬅️ Назад", "ad:menu"); await ctx.reply("Выберите дату:", { reply_markup: kb }); }

export function registerAdmin(bot: Bot, isOwner: OwnerCheck, clientMenu: (admin?: boolean) => Keyboard) {
  const guard = async (ctx: Context) => { if (!isOwner(ctx)) { if (ctx.callbackQuery) await ctx.answerCallbackQuery({ text: "Недостаточно прав", show_alert: true }); return false; } return true; };
  bot.command("admin", async ctx => { if (await guard(ctx)) await panel(ctx); });
  bot.hears("⚙️ Админ-панель", async ctx => { if (await guard(ctx)) await panel(ctx); });
  bot.hears("⬅️ В клиентское меню", async ctx => { if (await guard(ctx)) await ctx.reply("🐾 Клиентское меню", { reply_markup: clientMenu(true) }); });
  bot.hears("📅 Расписание", async ctx => { if (await guard(ctx)) await masterPicker(ctx, "ad:sch"); });
  bot.hears("📋 Записи", async ctx => { if (!(await guard(ctx))) return; const kb = new InlineKeyboard().text("📅 Сегодня", "ad:bookday:0").text("📅 Завтра", "ad:bookday:1").row().text("📆 Выбрать дату", "ad:bookpick").text("📋 Последние", "ad:bookall").row().text("⬅️ Назад", "ad:menu"); await ctx.reply("📋 Записи", { reply_markup: kb }); });
  bot.hears("➕ Добавить запись", async ctx => { if (!(await guard(ctx))) return; const clients = await prisma.user.findMany({ take: 20, orderBy: { createdAt: "desc" } }); const kb = new InlineKeyboard(); clients.forEach(c => kb.text(c.firstName || c.username || c.telegramId.toString(), `ad:newclient:${c.id}`).row()); kb.text("⬅️ Назад", "ad:menu"); await ctx.reply("Выберите клиента (показаны последние 20):", { reply_markup: kb }); });
  bot.hears("👩 Мастера", async ctx => { if (!(await guard(ctx))) return; const rows = await prisma.master.findMany({ include: { services: { include: { service: true } } }, orderBy: { name: "asc" } }); const kb = new InlineKeyboard().text("➕ Добавить мастера", "ad:masteradd").row(); rows.forEach(x => kb.text(`${x.isActive ? "👩" : "⚪"} ${x.name}`, `ad:master:${x.id}`).row()); kb.text("⬅️ Назад", "ad:menu"); await ctx.reply(rows.length ? "👩 Мастера:" : "Мастеров пока нет.", { reply_markup: kb }); });
  bot.hears("✂️ Услуги", async ctx => { if (!(await guard(ctx))) return; const rows = await prisma.service.findMany({ include: { category: true }, orderBy: { sortOrder: "asc" } }); const kb = new InlineKeyboard().text("➕ Добавить услугу", "ad:serviceadd").row(); rows.forEach(x => kb.text(`${x.isActive ? "✂️" : "⚪"} ${x.name}`, `ad:service:${x.id}`).row()); kb.text("⬅️ Назад", "ad:menu"); await ctx.reply(rows.length ? "✂️ Услуги:" : "Услуг пока нет. Добавьте первую.", { reply_markup: kb }); });
  bot.hears("💰 Цены", async ctx => { if (!(await guard(ctx))) return; const rows = await prisma.service.findMany({ where: { isArchived: false }, orderBy: { name: "asc" } }); const kb = new InlineKeyboard(); rows.forEach(x => kb.text(`${x.name} — ${money(x.priceKopecks)}`, `ad:price:${x.id}`).row()); kb.text("⬅️ Назад", "ad:menu"); await ctx.reply("💰 Выберите услугу для изменения цены:", { reply_markup: kb }); });
  bot.hears("👥 Клиенты", async ctx => { if (!(await guard(ctx))) return; const rows = await prisma.user.findMany({ include: { _count: { select: { pets: true, bookings: true } } }, orderBy: { createdAt: "desc" }, take: 20 }); const kb = new InlineKeyboard().text("🔎 Найти клиента", "ad:findclient").row(); rows.forEach(x => kb.text(`${x.firstName || x.username || x.telegramId.toString()} · 🐾${x._count.pets}`, `ad:client:${x.id}`).row()); kb.text("⬅️ Назад", "ad:menu"); await ctx.reply("👥 Клиенты (последние 20):", { reply_markup: kb }); });
  bot.hears("🐶 Питомцы", async ctx => { if (!(await guard(ctx))) return; const rows = await prisma.pet.findMany({ where: { isArchived: false }, include: { owner: true }, orderBy: { createdAt: "desc" }, take: 25 }); const kb = new InlineKeyboard(); rows.forEach(x => kb.text(`🐾 ${x.name} · ${x.owner.firstName || "владелец"}`, `ad:pet:${x.id}`).row()); kb.text("⬅️ Назад", "ad:menu"); await ctx.reply("🐶 Питомцы (последние 25):", { reply_markup: kb }); });
  bot.hears("🚫 Заблокированные окна", async ctx => { if (await guard(ctx)) await masterPicker(ctx, "ad:blocks"); });
  bot.hears("📊 Статистика", async ctx => { if (!(await guard(ctx))) return; const now = new Date(), week = new Date(now.getTime() - 7 * 86400000), month = new Date(now.getTime() - 30 * 86400000); const [todayCount, weekCount, monthCount, cancelled, completed, noShow, users, pets, popular] = await Promise.all([prisma.booking.count({ where: { startsAt: { gte: new Date(now.setHours(0,0,0,0)) } } }), prisma.booking.count({ where: { startsAt: { gte: week } } }), prisma.booking.count({ where: { startsAt: { gte: month } } }), prisma.booking.count({ where: { status: "CANCELLED" } }), prisma.booking.count({ where: { status: "COMPLETED" } }), prisma.booking.count({ where: { status: "NO_SHOW" } }), prisma.user.count(), prisma.pet.count(), prisma.booking.groupBy({ by: ["serviceId"], _count: { serviceId: true }, orderBy: { _count: { serviceId: "desc" } }, take: 3 })]); const names = await prisma.service.findMany({ where: { id: { in: popular.map(x => x.serviceId) } }, select: { id: true, name: true } }); await ctx.reply(`📊 Статистика\n\nСегодня: ${todayCount}\nЗа неделю: ${weekCount}\nЗа месяц: ${monthCount}\nОтмен: ${cancelled}\nЗавершено: ${completed}\nNo-show: ${noShow}\nКлиентов: ${users}\nПитомцев: ${pets}\n\nПопулярное:\n${popular.map(x => `• ${names.find(n => n.id === x.serviceId)?.name ?? "Услуга"} — ${x._count.serviceId}`).join("\n") || "—"}`, { reply_markup: back() }); });
  bot.hears("⚙️ Настройки", async ctx => { if (!(await guard(ctx))) return; const kb = new InlineKeyboard().text("Название", "ad:set:name").text("Адрес", "ad:set:address").row().text("Телефон", "ad:set:phone").text("Часовой пояс", "ad:set:timezone").row().text("Приветствие", "ad:set:welcomeText").text("Текст после записи", "ad:set:bookingSuccessText").row().text("⬅️ Назад", "ad:menu"); await ctx.reply("⚙️ Настройки бизнеса (секреты и токены здесь недоступны):", { reply_markup: kb }); });

  bot.callbackQuery(/^ad:(.+)$/, async ctx => { if (!(await guard(ctx))) return; const parts = ctx.match[1].split(":"); const [action, a, b] = parts; const user = await prisma.user.findUniqueOrThrow({ where: { telegramId: BigInt(ctx.from!.id) } }); await ctx.answerCallbackQuery();
    if (action === "menu") return void panel(ctx);
    if (action === "home") return void ctx.reply("🐾 Клиентское меню", { reply_markup: clientMenu(true) });
    if (action === "sch") return void datePicker(ctx, `ad:schdate:${a}`);
    if (action === "schdate") { const master = await prisma.master.findUniqueOrThrow({ where: { id: a } }); const cfg = await settings(), start = studioDateTime(b, 0, cfg.timezone), end = studioDateTime(day(b, 1), 0, cfg.timezone); const [bookings, blocks, windows] = await Promise.all([prisma.booking.findMany({ where: { masterId: a, status: { in: [...ACTIVE] }, startsAt: { lt: end }, endsAt: { gt: start } }, include: { pet: true } }), prisma.blockedTime.findMany({ where: { masterId: a, startsAt: { lt: end }, endsAt: { gt: start } } }), prisma.availabilityWindow.findMany({ where: { masterId: a, startsAt: { lt: end }, endsAt: { gt: start } } })]); const lines = [`📅 ${master.name} · ${dateLabel(b)}`]; for (let min = 0; min < 1440; min += cfg.bookingIntervalMinutes) { const at = studioDateTime(b, min, cfg.timezone), next = new Date(at.getTime() + cfg.bookingIntervalMinutes * 60000); const booking = bookings.find(x => x.startsAt < next && x.endsAt > at), block = blocks.find(x => x.startsAt < next && x.endsAt > at), window = windows.find(x => x.startsAt <= at && x.endsAt >= next); if (booking) lines.push(`${clock(min)} 🔴 ${booking.pet.name}`); else if (block) lines.push(`${clock(min)} ${block.kind === "BREAK" ? "🟡 Перерыв" : "⚫ Заблокировано"}`); else if (window) lines.push(`${clock(min)} 🟢 Свободное окно`); } const kb = new InlineKeyboard().text("➕ Добавить окно", `ad:addwin:${a}:${b}`).text("🚫 Заблокировать", `ad:block:${a}:${b}`).row().text("⚙️ Изменить день", `ad:day:${a}:${b}`).row().text("⬅️ К мастерам", "ad:schedule").text("⚙️ Админ-панель", "ad:menu"); return void ctx.reply(lines.join("\n") + "\n\nПоказываются разовые окна, блокировки и записи.", { reply_markup: kb }); }
    if (action === "schedule") return void masterPicker(ctx, "ad:sch");
    if (action === "addwin" || action === "block") { await setFlow(user.id, action, { masterId: a, date: b }); return void ctx.reply(action === "addwin" ? "Введите время окна в формате 09:00-10:00:" : "Введите период блокировки в формате 09:00-10:00:", { reply_markup: back() }); }
    if (action === "day") { await setFlow(user.id, "day", { masterId: a, date: b }); return void ctx.reply("Введите часы дня `09:00-18:00`, либо `выходной`.", { parse_mode: "Markdown", reply_markup: back() }); }
    if (action === "blocks") { const cfg = await settings(), from = studioDateTime(await today(), 0, cfg.timezone), rows = await prisma.blockedTime.findMany({ where: { masterId: a, endsAt: { gte: from } }, orderBy: { startsAt: "asc" }, take: 20 }); const kb = new InlineKeyboard(); rows.forEach(x => kb.text(`🗑 ${x.startsAt.toLocaleDateString("ru-RU", { timeZone: cfg.timezone })} ${x.startsAt.toLocaleTimeString("ru-RU", { timeZone: cfg.timezone, hour:"2-digit", minute:"2-digit" })}`, `ad:unblock:${x.id}`).row()); kb.text("⬅️ Назад", "ad:menu"); return void ctx.reply(rows.length ? "🚫 Блокировки — нажмите для снятия:" : "Активных блокировок нет.", { reply_markup: kb }); }
    if (action === "unblock") { await prisma.blockedTime.delete({ where: { id: a } }); return void ctx.reply("✅ Блокировка снята.", { reply_markup: back() }); }
    if (action === "bookpick") return void datePicker(ctx, "ad:bookdate");
    if (action === "bookday" || action === "bookdate" || action === "bookall") { const cfg = await settings(); const where = action === "bookall" ? {} : (() => { const d = action === "bookday" ? day(dateInZone(new Date(), cfg.timezone), Number(a)) : a; return { startsAt: { gte: studioDateTime(d, 0, cfg.timezone), lt: studioDateTime(day(d,1), 0, cfg.timezone) } }; })(); const rows = await prisma.booking.findMany({ where, include: { client:true, pet:true, service:true, master:true }, orderBy:{startsAt:"asc"}, take: 40 }); const kb = new InlineKeyboard(); rows.forEach(x => kb.text(`${x.startsAt.toLocaleDateString("ru-RU", {timeZone:cfg.timezone})} ${x.pet.name} · ${status(x.status)}`, `ad:booking:${x.id}`).row()); kb.text("⬅️ Назад", "ad:menu"); return void ctx.reply(rows.length ? "📋 Выберите запись:" : "Записей нет.", { reply_markup: kb }); }
    if (action === "booking") { const x = await prisma.booking.findUniqueOrThrow({ where:{id:a}, include:{client:true,pet:true,service:true,master:true} }); const kb = new InlineKeyboard().text("✅ Подтвердить", `ad:status:${a}:CONFIRMED`).text("❌ Отменить", `ad:status:${a}:CANCELLED`).row().text("✔️ Завершить", `ad:status:${a}:COMPLETED`).text("🚫 No-show", `ad:status:${a}:NO_SHOW`).row().text("⬅️ Записи", "ad:bookall"); return void ctx.reply(`📋 Запись\n\nКлиент: ${x.client.firstName || "—"}${x.client.username ? ` (@${x.client.username})` : ""}\nПитомец: ${x.pet.name}\nУслуга: ${x.service.name}\nМастер: ${x.master.name}\nКогда: ${x.startsAt.toLocaleString("ru-RU")}\nСтатус: ${status(x.status)}`, { reply_markup: kb }); }
    if (action === "status") { const x = await prisma.booking.update({ where:{id:a}, data:{status:b as never}, include:{client:true,service:true,master:true} }); if (["CONFIRMED", "CANCELLED"].includes(b)) await bot.api.sendMessage(x.client.telegramId.toString(), b === "CONFIRMED" ? `✅ Ваша запись подтверждена\n${x.service.name} · ${x.master.name}` : "❌ Ваша запись отменена администратором."); return void ctx.reply(`✅ Статус: ${status(b)}.`, { reply_markup: back() }); }
    if (action === "newclient") { const pets = await prisma.pet.findMany({where:{ownerId:a,isArchived:false}}); const kb=new InlineKeyboard(); pets.forEach(x=>kb.text(x.name,`ad:newpet:${x.id}`).row()); kb.text("⬅️ Назад","ad:menu"); return void ctx.reply("Выберите питомца:",{reply_markup:kb}); }
    if (action === "newpet") { const pet = await prisma.pet.findUniqueOrThrow({where:{id:a}}), services = await prisma.service.findMany({where:{isActive:true,isArchived:false,animalTypes:{has:pet.species}}}); const kb=new InlineKeyboard(); services.forEach(x=>kb.text(`${x.name} — ${money(x.priceKopecks)}`,`ad:newservice:${pet.id}:${x.id}`).row()); return void ctx.reply("Выберите услугу:",{reply_markup:kb}); }
    if (action === "newservice") { const masters=await prisma.master.findMany({where:{isActive:true,isArchived:false,services:{some:{serviceId:b}}}}); const kb=new InlineKeyboard(); masters.forEach(x=>kb.text(x.name,`ad:newmaster:${a}:${b}:${x.id}`).row()); return void ctx.reply("Выберите мастера:",{reply_markup:kb}); }
    if (action === "newmaster") { await setFlow(user.id,"newdate",{petId:a,serviceId:b,masterId:parts[3]}); return void datePicker(ctx,"ad:newdatepick"); }
    if (action === "newdatepick") { const f=await flow(user.id); if(!f) return; const slots=await availableSlots(f.masterId,f.serviceId,a),kb=new InlineKeyboard(); slots.forEach((x,i)=>{kb.text(clock(x.minutes),`ad:newtime:${x.minutes}`);if(i%4===3)kb.row();}); await setFlow(user.id,"newtime",{...f,date:a}); return void ctx.reply(slots.length?"Выберите время:":"Нет доступного времени.",{reply_markup:kb}); }
    if (action === "newtime") { const f=await flow(user.id); if(!f)return; const cfg=await settings(); try { const pet=await prisma.pet.findUniqueOrThrow({where:{id:f.petId}}); const booking=await createBooking({clientId:pet.ownerId,petId:f.petId,serviceId:f.serviceId,masterId:f.masterId,startsAt:studioDateTime(f.date,Number(a),cfg.timezone)}); await clearFlow(user.id); return void ctx.reply(`✅ Запись создана: ${booking.pet.name}, ${f.date} ${clock(Number(a))}.`,{reply_markup:back()}); } catch(e) { return void ctx.reply(e instanceof SlotTakenError?"❌ Слот уже занят.":"Не удалось создать запись."); } }
    if (action === "masteradd") { await setFlow(user.id,"masteradd"); return void ctx.reply("Введите имя мастера:", {reply_markup:back()}); }
    if (action === "master") { const x=await prisma.master.findUniqueOrThrow({where:{id:a},include:{services:{include:{service:true}}}}); const kb=new InlineKeyboard().text(x.isActive?"Выключить":"Включить",`ad:mastertoggle:${a}`).row().text("🗑️ Архивировать",`ad:masterarchive:${a}`).row().text("⬅️ Назад","ad:menu"); return void ctx.reply(`👩 ${x.name}\n${x.description||""}\nУслуги: ${x.services.map(s=>s.service.name).join(", ")||"не назначены"}`,{reply_markup:kb}); }
    if (action === "mastertoggle") { const x=await prisma.master.findUniqueOrThrow({where:{id:a}}); await prisma.master.update({where:{id:a},data:{isActive:!x.isActive}}); return void ctx.reply("✅ Статус мастера изменён.",{reply_markup:back()}); }
    if (action === "masterarchive") { await prisma.master.update({where:{id:a},data:{isArchived:true,isActive:false}}); return void ctx.reply("✅ Мастер архивирован.",{reply_markup:back()}); }
    if (action === "serviceadd") { const cats=await prisma.serviceCategory.findMany({where:{isArchived:false}}); if(!cats.length){await setFlow(user.id,"categoryadd");return void ctx.reply("Сначала введите название категории услуг:");} const kb=new InlineKeyboard();cats.forEach(x=>kb.text(x.name,`ad:servicecat:${x.id}`).row());return void ctx.reply("Выберите категорию:",{reply_markup:kb}); }
    if (action === "servicecat") { await setFlow(user.id,"servicename",{categoryId:a}); return void ctx.reply("Введите название услуги:"); }
    if (action === "service") { const x=await prisma.service.findUniqueOrThrow({where:{id:a}}),kb=new InlineKeyboard().text("💰 Изменить цену",`ad:price:${a}`).text(x.isActive?"Выключить":"Включить",`ad:servicetoggle:${a}`).row().text("🗑️ Архивировать",`ad:servicearchive:${a}`).row().text("⬅️ Назад","ad:menu"); return void ctx.reply(`✂️ ${x.name}\n${money(x.priceKopecks)} · ${x.durationMinutes} мин.\n${x.description||""}`,{reply_markup:kb}); }
    if (action === "price") { await setFlow(user.id,"price",{serviceId:a}); return void ctx.reply("Введите новую цену в рублях, например: 4000"); }
    if (action === "servicetoggle") { const x=await prisma.service.findUniqueOrThrow({where:{id:a}});await prisma.service.update({where:{id:a},data:{isActive:!x.isActive}});return void ctx.reply("✅ Видимость услуги изменена.",{reply_markup:back()}); }
    if (action === "servicearchive") {await prisma.service.update({where:{id:a},data:{isArchived:true,isActive:false}});return void ctx.reply("✅ Услуга архивирована.",{reply_markup:back()});}
    if (action === "client") { const x=await prisma.user.findUniqueOrThrow({where:{id:a},include:{pets:{where:{isArchived:false}},_count:{select:{bookings:true}}}});const kb=new InlineKeyboard().text("🐾 Питомцы",`ad:clientpets:${a}`).text("📋 История записей",`ad:clienthistory:${a}`).row().text("✉️ Написать",`ad:clientmessage:${a}`).text(x.isBlocked?"✅ Разблокировать":"🚫 Заблокировать",`ad:clientblock:${a}`).row().text("◀️ Назад","ad:menu");return void ctx.reply(`👤 <b>${x.firstName||"Клиент"}</b>\n\nTelegram ID: ${x.telegramId}\nUsername: ${x.username?`@${x.username}`:"—"}\n📱 Телефон: ${x.phone||"—"}\n\n🐾 Питомцы: ${x.pets.length}\n${x.pets.map(p=>`${p.species==="cat"?"🐱":"🐶"} ${p.name} — ${p.breed||"порода не указана"}`).join("\n")||"—"}\n\n📅 Записей: ${x._count.bookings}`,{parse_mode:"HTML",reply_markup:kb}); }
    if (action === "clientpets") { const pets=await prisma.pet.findMany({where:{ownerId:a,isArchived:false},orderBy:{name:"asc"}});const kb=new InlineKeyboard();pets.forEach(p=>kb.text(p.name,`ad:pet:${p.id}`).row());kb.text("◀️ К клиенту",`ad:client:${a}`);return void ctx.reply(pets.length?"🐾 Питомцы клиента:":"Питомцев нет.",{reply_markup:kb}); }
    if (action === "clienthistory") { const rows=await prisma.booking.findMany({where:{clientId:a},include:{pet:true,service:true},orderBy:{startsAt:"desc"},take:30});const kb=new InlineKeyboard().text("◀️ К клиенту",`ad:client:${a}`);return void ctx.reply(rows.length?`📋 История записей:\n\n${rows.map(x=>`${x.startsAt.toLocaleDateString("ru-RU")} — ${x.pet.name} — ${x.service.name} — ${status(x.status)}`).join("\n")}`:"Записей нет.",{reply_markup:kb}); }
    if (action === "clientmessage") { const x=await prisma.user.findUniqueOrThrow({where:{id:a}});return void ctx.reply(`Откройте диалог с клиентом в Telegram: ${x.username?`@${x.username}`:`Telegram ID ${x.telegramId}`}`,{reply_markup:new InlineKeyboard().text("◀️ К клиенту",`ad:client:${a}`)}); }
    if (action === "clientblock") { const x=await prisma.user.update({where:{id:a},data:{isBlocked:{set:!(await prisma.user.findUniqueOrThrow({where:{id:a},select:{isBlocked:true}})).isBlocked}}});return void ctx.reply(x.isBlocked?"✅ Клиент заблокирован.":"✅ Клиент разблокирован.",{reply_markup:new InlineKeyboard().text("◀️ К клиенту",`ad:client:${a}`)}); }
    if (action === "pet") { const x=await prisma.pet.findUniqueOrThrow({where:{id:a},include:{owner:true,bookings:{include:{service:true},orderBy:{startsAt:"desc"},take:5}}});return void ctx.reply(`🐶 ${x.name}\nВид: ${x.species}\nПорода: ${x.breed||"—"}\nПол: ${x.sex||"—"}\nВладелец: ${x.owner.firstName||"—"}\nЗаметки: ${x.notes||"—"}\n\nИстория:\n${x.bookings.map(y=>`• ${y.service.name} · ${status(y.status)}`).join("\n")||"—"}`,{reply_markup:back()}); }
    if (action === "findclient") {await setFlow(user.id,"findclient");return void ctx.reply("Введите имя, username, Telegram ID или номер телефона:");}
    if (action === "set") {await setFlow(user.id,"setting",{field:a});return void ctx.reply(`Введите новое значение для «${a}»:`);}
  });
  bot.on("message:text", async (ctx, next) => { if (!isOwner(ctx)) return next(); const user = await prisma.user.findUnique({where:{telegramId:BigInt(ctx.from.id)}}); if(!user) return next(); const f=await flow(user.id); if(!f) return next(); const state=(await prisma.botFlow.findUnique({where:{userId:user.id}}))!.state.slice(6), text=ctx.message.text.trim();
    if(state==="masteradd"){const services=await prisma.service.findMany({where:{isActive:true,isArchived:false},select:{id:true}});await prisma.master.create({data:{name:text,services:{create:services.map(service=>({serviceId:service.id}))}}});await clearFlow(user.id);await ctx.reply(services.length?"✅ Мастер добавлен; ему назначены текущие активные услуги.":"✅ Мастер добавлен. Добавьте услуги и затем создайте/настройте мастера.",{reply_markup:adminKeyboard()});return;}
    if(state==="categoryadd"){const c=await prisma.serviceCategory.create({data:{name:text}});await setFlow(user.id,"servicename",{categoryId:c.id});await ctx.reply("Введите название услуги:");return;}
    if(state==="servicename"){await setFlow(user.id,"serviceprice",{...f,name:text});await ctx.reply("Введите цену в рублях:");return;}
    if(state==="serviceprice"){const amount=Number(text.replace(",","."));if(!Number.isFinite(amount)||amount<0)return void ctx.reply("Введите корректную цену числом.");await setFlow(user.id,"serviceduration",{...f,price:String(Math.round(amount*100))});await ctx.reply("Введите длительность в минутах, например 120:");return;}
    if(state==="serviceduration"){const duration=Number(text);if(!Number.isInteger(duration)||duration<15)return void ctx.reply("Введите длительность не менее 15 минут.");await prisma.service.create({data:{categoryId:f.categoryId,name:f.name,priceKopecks:Number(f.price),durationMinutes:duration,animalTypes:["dog","cat"]}});await clearFlow(user.id);await ctx.reply("✅ Услуга добавлена для собак и кошек.",{reply_markup:adminKeyboard()});return;}
    if(state==="price"){const value=Number(text.replace(",","."));if(!Number.isFinite(value)||value<0)return void ctx.reply("Введите корректную цену.");await prisma.service.update({where:{id:f.serviceId},data:{priceKopecks:Math.round(value*100)}});await clearFlow(user.id);await ctx.reply("✅ Цена обновлена.",{reply_markup:adminKeyboard()});return;}
    if(state==="setting"){const allowed=["name","address","phone","timezone","welcomeText","bookingSuccessText"];if(!allowed.includes(f.field))return;await prisma.studioSettings.update({where:{id:1},data:{[f.field]:text}});await clearFlow(user.id);await ctx.reply("✅ Настройка сохранена.",{reply_markup:adminKeyboard()});return;}
    if(state==="findclient"){const digits=text.replace(/\D/g,"");const telegramMatch=digits.length>0&&digits.length<=19?[{telegramId:BigInt(digits)}]:[];const rows=await prisma.user.findMany({where:{OR:[{firstName:{contains:text,mode:"insensitive"}},{username:{contains:text.replace(/^@/,""),mode:"insensitive"}},{phone:{contains:text,mode:"insensitive"}},...telegramMatch]},take:20});const kb=new InlineKeyboard();rows.forEach(x=>kb.text(x.firstName||x.username||x.telegramId.toString(),`ad:client:${x.id}`).row());await clearFlow(user.id);await ctx.reply(rows.length?"Результаты:":"Ничего не найдено.",{reply_markup:kb});return;}
    if(state==="day"||state==="addwin"||state==="block"){const match=/^(\d{1,2}):(\d{2})-(\d{1,2}):(\d{2})$/.exec(text);const cfg=await settings();if(state==="day"&&text.toLowerCase()==="выходной"){await prisma.scheduleException.upsert({where:{masterId_date:{masterId:f.masterId,date:new Date(`${f.date}T00:00:00.000Z`)}},update:{isDayOff:true,startMinutes:null,endMinutes:null},create:{masterId:f.masterId,date:new Date(`${f.date}T00:00:00.000Z`),isDayOff:true}});await clearFlow(user.id);return void ctx.reply("✅ День сделан выходным.",{reply_markup:adminKeyboard()});}if(!match)return void ctx.reply("Формат: 09:00-18:00");const start=Number(match[1])*60+Number(match[2]),end=Number(match[3])*60+Number(match[4]);if(start<0||end>1440||end<=start)return void ctx.reply("Укажите корректный период.");const startsAt=studioDateTime(f.date,start,cfg.timezone),endsAt=studioDateTime(f.date,end,cfg.timezone);if(state==="day")await prisma.scheduleException.upsert({where:{masterId_date:{masterId:f.masterId,date:new Date(`${f.date}T00:00:00.000Z`)}},update:{isDayOff:false,startMinutes:start,endMinutes:end},create:{masterId:f.masterId,date:new Date(`${f.date}T00:00:00.000Z`),isDayOff:false,startMinutes:start,endMinutes:end}});else if(state==="addwin")await prisma.availabilityWindow.create({data:{masterId:f.masterId,startsAt,endsAt}});else {const booking=await prisma.booking.findFirst({where:{masterId:f.masterId,status:{in:[...ACTIVE]},startsAt:{lt:endsAt},endsAt:{gt:startsAt}},include:{client:true,pet:true}});if(booking)return void ctx.reply(`⚠️ На это время уже есть запись: ${booking.client.firstName||"клиент"}, ${booking.pet.name}. Сначала отмените или перенесите её через «📋 Записи».`);await prisma.blockedTime.create({data:{masterId:f.masterId,startsAt,endsAt}});}await clearFlow(user.id);await ctx.reply(state==="addwin"?"✅ Окно добавлено и доступно клиентам.":state==="block"?"✅ Время заблокировано.":"✅ Часы дня сохранены.",{reply_markup:adminKeyboard()});return;}
    return next();
  });
}
