import { Bot, Context, InlineKeyboard, Keyboard } from "grammy";
import { prisma } from "../lib/db";
import { clock, dateInZone, studioDateTime } from "../lib/time";
import { money, settings } from "../lib/settings";
import { availableSlots, createBooking, SlotTakenError } from "../services/availability";

type OwnerCheck = (ctx: Context) => boolean;
type AdminFlow = Record<string, string>;
const ACTIVE = ["PENDING", "CONFIRMED"] as const;
const label = (s: string) => ({ PENDING: "🟡 Ожидает", CONFIRMED: "🟢 Подтверждена", CANCELLED: "🔴 Отменена", COMPLETED: "⚪ Завершена", NO_SHOW: "⚫ Не пришёл" }[s] || s);
const icon = (s: string) => s === "cat" ? "🐱" : "🐶";
const date = (d: string, n: number) => { const x = new Date(`${d}T12:00:00Z`); x.setUTCDate(x.getUTCDate() + n); return x.toISOString().slice(0, 10); };
const dayLabel = (d: string) => new Intl.DateTimeFormat("ru-RU", { day: "numeric", month: "long", timeZone: "UTC" }).format(new Date(`${d}T12:00:00Z`));
const nav = (back = "ad:home") => new InlineKeyboard().text("⬅️ Назад", back).text("🏠 Главная", "ad:home");
async function today() { return dateInZone(new Date(), (await settings()).timezone); }
async function getFlow(id: string) { const x = await prisma.botFlow.findUnique({ where: { userId: id } }); return x?.state.startsWith("admin:") ? x.payload as AdminFlow : null; }
async function setFlow(id: string, state: string, payload: AdminFlow = {}) { await prisma.botFlow.upsert({ where: { userId: id }, update: { state: `admin:${state}`, payload }, create: { userId: id, state: `admin:${state}`, payload } }); }
async function clearFlow(id: string) { await prisma.botFlow.deleteMany({ where: { userId: id } }); }
async function actor(ctx: Context) { return prisma.user.upsert({ where: { telegramId: BigInt(ctx.from!.id) }, update: {}, create: { telegramId: BigInt(ctx.from!.id), firstName: ctx.from!.first_name, username: ctx.from!.username } }); }
async function render(ctx: Context, text: string, kb?: InlineKeyboard) { if (ctx.callbackQuery?.message) { try { await ctx.editMessageText(text, { reply_markup: kb }); return; } catch (e) { if (e instanceof Error && e.message.includes("message is not modified")) return; } } await ctx.reply(text, { reply_markup: kb }); }
function homeKb() { return new InlineKeyboard().text("📅 Записи", "ad:bookings").text("👥 Клиенты", "ad:clients").row().text("🐾 Питомцы", "ad:pets").text("📊 Статистика", "ad:stats").row().text("✂️ Услуги", "ad:services").text("👩 Мастера", "ad:masters").row().text("💰 Цены", "ad:prices").text("🚫 Блокировки", "ad:blocks").row().text("🗓 Расписание", "ad:schedule").text("➕ Создать запись", "ad:newbooking").row().text("📢 Рассылка", "ad:broadcast").row().text("⚙️ Настройки", "ad:settings").row().text("⬅️ Клиентское меню", "ad:clientmenu"); }
async function dashboard(ctx: Context) { const cfg = await settings(), d = await today(), from = studioDateTime(d, 0, cfg.timezone), to = studioDateTime(date(d, 1), 0, cfg.timezone), where = { startsAt: { gte: from, lt: to } }; const [all, pending, confirmed, users, pets, sum] = await Promise.all([prisma.booking.count({ where }), prisma.booking.count({ where: { ...where, status: "PENDING" } }), prisma.booking.count({ where: { ...where, status: "CONFIRMED" } }), prisma.user.count(), prisma.pet.count({ where: { isArchived: false } }), prisma.booking.aggregate({ _sum: { priceKopecks: true }, where: { ...where, status: { not: "CANCELLED" } } })]); await render(ctx, `⚙️ ЛАПУНЯ\nАДМИН-ПАНЕЛЬ\n\n📅 Сегодня\n• Записей: ${all}\n• Ожидают: ${pending}\n• Подтверждены: ${confirmed}\n\n👥 Клиенты\n• Клиентов: ${users}\n• Питомцев: ${pets}\n\n💰 Сегодня\n• Выручка: ${money(sum._sum.priceKopecks || 0, cfg.currency)}`, homeKb()); }
async function dates(ctx: Context, prefix: string, back = "ad:home") { const base = await today(), kb = new InlineKeyboard(); for (let i = 0; i < 14; i++) { const d = date(base, i); kb.text(dayLabel(d), `${prefix}:${d}`); if (i % 2) kb.row(); } kb.row().text("⬅️ Назад", back).text("🏠 Главная", "ad:home"); await render(ctx, "📅 Выберите дату:", kb); }
async function masters(ctx: Context, prefix: string, back = "ad:home") { const rows = await prisma.master.findMany({ where: { isArchived: false }, orderBy: { name: "asc" } }), kb = new InlineKeyboard(); rows.forEach(x => kb.text(`${x.isActive ? "👩" : "⚪"} ${x.name}`, `${prefix}:${x.id}`).row()); kb.text("⬅️ Назад", back).text("🏠 Главная", "ad:home"); await render(ctx, rows.length ? "👩 Выберите мастера:" : "Мастеров пока нет.", kb); }
async function scheduleOverview(ctx: Context, d: string) { const cfg = await settings(), start = studioDateTime(d, 0, cfg.timezone), end = studioDateTime(date(d, 1), 0, cfg.timezone), weekday = start.getUTCDay(); const rows = await prisma.master.findMany({ where: { isArchived: false }, include: { schedules: true, exceptions: true, bookings: { where: { status: { in: [...ACTIVE] }, startsAt: { lt: end }, endsAt: { gt: start } } }, blocks: { where: { startsAt: { lt: end }, endsAt: { gt: start } } } }, orderBy: { name: "asc" } }); const kb = new InlineKeyboard(); const lines = [`📅 РАСПИСАНИЕ\n\n${dayLabel(d)}`]; for (const master of rows) { const exception = master.exceptions.find(x => x.date.toISOString().slice(0, 10) === d), rule = master.schedules.find(x => x.weekday === weekday && x.isWorking), from = exception?.startMinutes ?? rule?.startMinutes, to = exception?.endMinutes ?? rule?.endMinutes, hours = exception?.isDayOff || from === undefined || to === undefined ? "⚪ Выходной" : `🟢 ${clock(from)}–${clock(to)}`; lines.push(`\n👩 ${master.name}\n${hours}\n📋 Записей: ${master.bookings.length} · 🚫 Блокировок: ${master.blocks.length}`); kb.text(`👩 ${master.name}`, `ad:schdate:${master.id}:${d}`).row(); } kb.text("◀️ Предыдущий день", `ad:scheduledate:${date(d, -1)}`).text("▶️ Следующий день", `ad:scheduledate:${date(d, 1)}`).row().text("📆 Выбрать дату", "ad:schedulepick").text("🚫 Блокировки", "ad:blocks").row().text("👩 Мастера", "ad:masters").text("🏠 Главная", "ad:home"); await render(ctx, rows.length ? lines.join("\n") : "📅 РАСПИСАНИЕ\n\nМастеров пока нет.", kb); }
async function scheduleDay(ctx: Context, masterId: string, d: string) { const master = await prisma.master.findUnique({ where: { id: masterId }, include: { schedules: true, exceptions: true } }); if (!master) return void await render(ctx, "Мастер не найден.", nav("ad:schedule")); const cfg = await settings(), start = studioDateTime(d, 0, cfg.timezone), end = studioDateTime(date(d, 1), 0, cfg.timezone), weekday = start.getUTCDay(), [booked, blocked, windows] = await Promise.all([prisma.booking.findMany({ where: { masterId, status: { in: [...ACTIVE] }, startsAt: { lt: end }, endsAt: { gt: start } }, include: { pet: true, service: true }, orderBy: { startsAt: "asc" } }), prisma.blockedTime.findMany({ where: { masterId, startsAt: { lt: end }, endsAt: { gt: start } }, orderBy: { startsAt: "asc" } }), prisma.availabilityWindow.findMany({ where: { masterId, startsAt: { lt: end }, endsAt: { gt: start } } })]); const exception = master.exceptions.find(x => x.date.toISOString().slice(0, 10) === d), rule = master.schedules.find(x => x.weekday === weekday && x.isWorking), from = exception?.startMinutes ?? rule?.startMinutes, to = exception?.endMinutes ?? rule?.endMinutes; const hours = exception?.isDayOff || from === undefined || to === undefined ? "⚪ Выходной" : `🟢 Рабочий день: ${clock(from)}–${clock(to)}`; const lines = [`📅 ${master.name} · ${dayLabel(d)}`, hours, `\n📋 Записи: ${booked.length}`, ...booked.map(x => `🔴 ${x.startsAt.toLocaleTimeString("ru-RU", { timeZone: cfg.timezone, hour: "2-digit", minute: "2-digit" })}–${x.endsAt.toLocaleTimeString("ru-RU", { timeZone: cfg.timezone, hour: "2-digit", minute: "2-digit" })} · ${x.pet.name} · ${x.service.name}`), `\n🚫 Блокировки: ${blocked.length}`, ...blocked.map(x => `⚫ ${x.startsAt.toLocaleTimeString("ru-RU", { timeZone: cfg.timezone, hour: "2-digit", minute: "2-digit" })}–${x.endsAt.toLocaleTimeString("ru-RU", { timeZone: cfg.timezone, hour: "2-digit", minute: "2-digit" })}`), windows.length ? `\n➕ Дополнительные окна: ${windows.length}` : ""]; const kb = new InlineKeyboard().text("➕ Настроить рабочий день", `ad:day:${masterId}:${d}`).text("🚫 Заблокировать время", `ad:block:${masterId}:${d}`).row().text("➕ Дополнительное окно", `ad:addwin:${masterId}:${d}`).text("📋 Записи на день", `ad:schbookings:${masterId}:${d}`).row().text("◀️ День", `ad:schdate:${masterId}:${date(d, -1)}`).text("▶️ День", `ad:schdate:${masterId}:${date(d, 1)}`).row().text("⬅️ К расписанию", `ad:scheduledate:${d}`).text("🏠 Главная", "ad:home"); await render(ctx, lines.filter(Boolean).join("\n"), kb); }

export function registerAdmin(bot: Bot, isOwner: OwnerCheck, clientMenu: (admin?: boolean) => Keyboard) {
  const guard = async (ctx: Context) => { if (isOwner(ctx)) return true; if (ctx.callbackQuery) await ctx.answerCallbackQuery({ text: "Недостаточно прав", show_alert: true }); return false; };
  bot.command("admin", async ctx => { if (await guard(ctx)) await dashboard(ctx); });
  bot.hears("⚙️ Админ-панель", async ctx => { if (await guard(ctx)) await dashboard(ctx); });
  bot.hears("⬅️ В клиентское меню", async ctx => { if (await guard(ctx)) await ctx.reply("🐾 Клиентское меню", { reply_markup: clientMenu(true) }); });
  // Old Reply Keyboard labels remain safe entry points, but every new screen is inline-only.
  bot.hears("📅 Расписание", async ctx => { if (await guard(ctx)) await scheduleOverview(ctx, await today()); });
  bot.hears("📋 Записи", async ctx => { if (await guard(ctx)) await render(ctx, "📅 ЗАПИСИ", new InlineKeyboard().text("Сегодня", "ad:bookday:0").text("Завтра", "ad:bookday:1").row().text("Эта неделя", "ad:bookweek").text("📆 Другая дата", "ad:bookpick").row().text("⬅️ Назад", "ad:home")); });
  bot.hears("👥 Клиенты", async ctx => { if (await guard(ctx)) await render(ctx, "👥 КЛИЕНТЫ", new InlineKeyboard().text("Открыть клиентов", "ad:clients").row().text("🏠 Главная", "ad:home")); });
  bot.hears("🐶 Питомцы", async ctx => { if (await guard(ctx)) await render(ctx, "🐾 ПИТОМЦЫ", new InlineKeyboard().text("Открыть питомцев", "ad:pets").row().text("🏠 Главная", "ad:home")); });
  bot.hears("✂️ Услуги", async ctx => { if (await guard(ctx)) await render(ctx, "✂️ УСЛУГИ", new InlineKeyboard().text("Открыть услуги", "ad:services").row().text("🏠 Главная", "ad:home")); });
  bot.hears("💰 Цены", async ctx => { if (await guard(ctx)) await render(ctx, "💰 ЦЕНЫ", new InlineKeyboard().text("Открыть цены", "ad:prices").row().text("🏠 Главная", "ad:home")); });
  bot.hears("👩 Мастера", async ctx => { if (await guard(ctx)) await render(ctx, "👩 МАСТЕРА", new InlineKeyboard().text("Открыть мастеров", "ad:masters").row().text("🏠 Главная", "ad:home")); });
  bot.hears("🚫 Заблокированные окна", async ctx => { if (await guard(ctx)) await render(ctx, "🚫 ЗАБЛОКИРОВАННЫЕ ОКНА", new InlineKeyboard().text("Открыть блокировки", "ad:blocks").row().text("🏠 Главная", "ad:home")); });
  bot.hears("📊 Статистика", async ctx => { if (await guard(ctx)) await render(ctx, "📊 СТАТИСТИКА", new InlineKeyboard().text("Открыть статистику", "ad:stats").row().text("🏠 Главная", "ad:home")); });
  bot.hears("⚙️ Настройки", async ctx => { if (await guard(ctx)) await render(ctx, "⚙️ НАСТРОЙКИ", new InlineKeyboard().text("Открыть настройки", "ad:settings").row().text("🏠 Главная", "ad:home")); });
  bot.hears("➕ Добавить запись", async ctx => { if (await guard(ctx)) await render(ctx, "➕ СОЗДАТЬ ЗАПИСЬ", new InlineKeyboard().text("Выбрать клиента", "ad:newbooking").row().text("🏠 Главная", "ad:home")); });
  bot.callbackQuery(/^ad:(.+)$/, async ctx => {
    if (!(await guard(ctx))) return; await ctx.answerCallbackQuery(); const [action, a, b, c] = ctx.match[1].split(":"), admin = await actor(ctx);
    if (action === "home" || action === "menu") return void await dashboard(ctx);
    if (action === "clientmenu") { await render(ctx, "🐾 Клиентское меню"); return void await ctx.reply("Выберите действие:", { reply_markup: clientMenu(true) }); }
    if (action === "bookings") return void await render(ctx, "📅 ЗАПИСИ", new InlineKeyboard().text("Сегодня", "ad:bookday:0").text("Завтра", "ad:bookday:1").row().text("Эта неделя", "ad:bookweek").text("📆 Другая дата", "ad:bookpick").row().text("⬅️ Назад", "ad:home"));
    if (action === "bookpick") return void await dates(ctx, "ad:bookdate", "ad:bookings");
    if (["bookday", "bookdate", "bookweek", "bookall"].includes(action)) { const cfg = await settings(); let where = {}; if (action !== "bookall") { const startDay = action === "bookday" ? date(await today(), Number(a)) : action === "bookweek" ? await today() : a; where = { startsAt: { gte: studioDateTime(startDay, 0, cfg.timezone), lt: studioDateTime(date(startDay, action === "bookweek" ? 7 : 1), 0, cfg.timezone) } }; } const rows = await prisma.booking.findMany({ where, include: { client: true, pet: true }, orderBy: { startsAt: "asc" }, take: 50 }), kb = new InlineKeyboard(); rows.forEach(x => kb.text(`${x.status === "PENDING" ? "🟡" : x.status === "CONFIRMED" ? "🟢" : "⚪"} ${x.startsAt.toLocaleString("ru-RU", { timeZone: cfg.timezone, day: "2-digit", month: "2-digit", hour: "2-digit", minute: "2-digit" })} · ${x.client.firstName || "Клиент"} · ${x.pet.name}`, `ad:booking:${x.id}`).row()); kb.text("⬅️ Назад", "ad:bookings"); return void await render(ctx, rows.length ? "📅 ЗАПИСИ\n\nВыберите запись:" : "📅 Записей за этот период нет.", kb); }
    if (action === "booking") { const x = await prisma.booking.findUnique({ where: { id: a }, include: { client: true, pet: true, service: true, master: true } }); if (!x) return void await render(ctx, "Запись не найдена.", nav("ad:bookings")); const cfg = await settings(), kb = new InlineKeyboard(); if (ACTIVE.includes(x.status as typeof ACTIVE[number])) kb.text("✅ Подтвердить", `ad:status:${a}:CONFIRMED`).text("❌ Отменить", `ad:status:${a}:CANCELLED`).row(); kb.text("👤 Клиент", `ad:client:${x.clientId}`).text("🐾 Питомец", `ad:pet:${x.petId}`).row().text("⬅️ Назад", "ad:bookings"); return void await render(ctx, `📋 ЗАПИСЬ\n\n👤 Клиент: ${x.client.firstName || "—"}\n📱 Телефон: ${x.client.phone || "—"}\n🐾 Питомец: ${x.pet.name}\n✂️ Услуга: ${x.service.name}\n👩 Мастер: ${x.master.name}\n📅 Дата: ${x.startsAt.toLocaleDateString("ru-RU", { timeZone: cfg.timezone })}\n🕐 Время: ${x.startsAt.toLocaleTimeString("ru-RU", { timeZone: cfg.timezone, hour: "2-digit", minute: "2-digit" })}\n💰 Цена: ${money(x.priceKopecks, cfg.currency)}\n📌 Статус: ${label(x.status)}`, kb); }
    if (action === "status") { const result = await prisma.booking.updateMany({ where: { id: a, status: { in: [...ACTIVE] } }, data: { status: b as never } }); if (!result.count) return void await render(ctx, "⚠️ Эта запись уже обработана.", nav("ad:bookings")); const x = await prisma.booking.findUniqueOrThrow({ where: { id: a }, include: { client: true, service: true, master: true } }); if (["CONFIRMED", "CANCELLED"].includes(b)) try { await bot.api.sendMessage(x.client.telegramId.toString(), b === "CONFIRMED" ? `✅ Ваша запись подтверждена\n${x.service.name} · ${x.master.name}` : "❌ Ваша запись отменена администратором."); } catch {} return void await render(ctx, `✅ Статус обновлён: ${label(b)}.`, nav("ad:bookings")); }
    if (action === "clients") { const rows = await prisma.user.findMany({ include: { _count: { select: { pets: { where: { isArchived: false } } } } }, orderBy: { createdAt: "desc" }, take: 20 }), kb = new InlineKeyboard().text("🔎 Поиск клиента", "ad:findclient").row(); rows.forEach(x => kb.text(`👤 ${x.firstName || x.username || x.telegramId} · 🐾 ${x._count.pets}`, `ad:client:${x.id}`).row()); kb.text("⬅️ Назад", "ad:home"); return void await render(ctx, "👥 КЛИЕНТЫ\n\nПоследние клиенты:", kb); }
    if (action === "client") { const x = await prisma.user.findUnique({ where: { id: a }, include: { pets: { where: { isArchived: false } }, _count: { select: { bookings: true } } } }); if (!x) return void await render(ctx, "Клиент не найден.", nav("ad:clients")); const kb = new InlineKeyboard().text("🐾 Питомцы", `ad:clientpets:${a}`).text("📋 История", `ad:clienthistory:${a}`).row().text("💬 Написать", `ad:clientmessage:${a}`).text("✏️ Изменить", `ad:clientedit:${a}`).row().text(x.isBlocked ? "✅ Разблокировать" : "🚫 Заблокировать", `ad:clientblock:${a}`).row().text("⬅️ Назад", "ad:clients"); return void await render(ctx, `👤 КЛИЕНТ\n\nИмя: ${x.firstName || "—"}\n📱 ${x.phone || "—"}\nTelegram: ${x.username ? `@${x.username}` : "—"}\nID: ${x.telegramId}\n\n🐾 Питомцы: ${x.pets.length}\n📅 Записей: ${x._count.bookings}${x.isBlocked ? "\n\n🚫 Клиент заблокирован" : ""}`, kb); }
    if (action === "clientpets") { const rows = await prisma.pet.findMany({ where: { ownerId: a, isArchived: false }, orderBy: { name: "asc" } }), kb = new InlineKeyboard(); rows.forEach(x => kb.text(`${icon(x.species)} ${x.name}${x.breed ? ` · ${x.breed}` : ""}`, `ad:pet:${x.id}`).row()); kb.text("⬅️ К клиенту", `ad:client:${a}`); return void await render(ctx, rows.length ? "🐾 ПИТОМЦЫ КЛИЕНТА" : "🐾 Питомцев нет.", kb); }
    if (action === "clienthistory" || action === "pethistory") { const rows = await prisma.booking.findMany({ where: action === "clienthistory" ? { clientId: a } : { petId: a }, include: { pet: true, service: true, master: true }, orderBy: { startsAt: "desc" }, take: 20 }), cfg = await settings(); const txt = rows.map(x => `📅 ${x.startsAt.toLocaleDateString("ru-RU", { timeZone: cfg.timezone })} · 🕐 ${x.startsAt.toLocaleTimeString("ru-RU", { timeZone: cfg.timezone, hour: "2-digit", minute: "2-digit" })}\n🐾 ${x.pet.name} · ✂️ ${x.service.name}\n👩 ${x.master.name} · 💰 ${money(x.priceKopecks, cfg.currency)}\n📌 ${label(x.status)}`).join("\n\n"); return void await render(ctx, txt ? `📋 ИСТОРИЯ\n\n${txt}` : "📋 История пуста.", nav(action === "clienthistory" ? `ad:client:${a}` : `ad:pet:${a}`)); }
    if (action === "clientmessage") { await setFlow(admin.id, "clientmessage", { clientId: a }); return void await render(ctx, "💬 НАПИСАТЬ КЛИЕНТУ\n\nВведите сообщение для клиента:", new InlineKeyboard().text("❌ Отмена", `ad:flowcancel:client:${a}`)); }
    if (action === "flowcancel") { await clearFlow(admin.id); return void await render(ctx, "Действие отменено.", nav(`ad:${a}:${b}`)); }
    if (action === "clientmessagesend") { const f = await getFlow(admin.id); if (!f?.clientId || !f.text) return void await render(ctx, "Черновик сообщения не найден.", nav("ad:clients")); const target = await prisma.user.findUnique({ where: { id: f.clientId } }); if (!target) return void await render(ctx, "Клиент не найден.", nav("ad:clients")); try { await bot.api.sendMessage(target.telegramId.toString(), f.text); await clearFlow(admin.id); return void await render(ctx, "✅ Сообщение отправлено клиенту.", nav(`ad:client:${target.id}`)); } catch { return void await render(ctx, "❌ Не удалось отправить сообщение. Возможно, клиент заблокировал бота.", nav(`ad:client:${target.id}`)); } }
    if (action === "clientedit" || action === "petedit") { await setFlow(admin.id, action, { [action === "clientedit" ? "clientId" : "petId"]: a }); return void await render(ctx, action === "clientedit" ? "✏️ Введите новое имя клиента:" : "✏️ Введите новое имя питомца:", nav(action === "clientedit" ? `ad:client:${a}` : `ad:pet:${a}`)); }
    if (action === "clientblock") { const x = await prisma.user.findUniqueOrThrow({ where: { id: a } }); await prisma.user.update({ where: { id: a }, data: { isBlocked: !x.isBlocked } }); return void await render(ctx, x.isBlocked ? "✅ Клиент разблокирован." : "✅ Клиент заблокирован.", nav(`ad:client:${a}`)); }
    if (action === "pets") { const rows = await prisma.pet.findMany({ where: { isArchived: false }, include: { owner: true }, orderBy: { createdAt: "desc" }, take: 25 }), kb = new InlineKeyboard().text("🔎 Найти питомца", "ad:findpet").row(); rows.forEach(x => kb.text(`${icon(x.species)} ${x.name} · 👤 ${x.owner.firstName || "владелец"}`, `ad:pet:${x.id}`).row()); kb.text("⬅️ Назад", "ad:home"); return void await render(ctx, "🐾 ПИТОМЦЫ\n\nПоследние питомцы:", kb); }
    if (action === "pet") { const x = await prisma.pet.findUnique({ where: { id: a }, include: { owner: true, _count: { select: { bookings: true } } } }); if (!x) return void await render(ctx, "Питомец не найден.", nav("ad:pets")); const kb = new InlineKeyboard().text("📋 История", `ad:pethistory:${a}`).text("✏️ Изменить", `ad:petedit:${a}`).row().text("👤 Владелец", `ad:client:${x.ownerId}`).row().text("⬅️ Назад", "ad:pets"); return void await render(ctx, `${icon(x.species)} ${x.name.toUpperCase()}\n\nВид: ${x.species === "cat" ? "Кошка" : "Собака"}\nПорода: ${x.breed || "—"}\nВладелец: ${x.owner.firstName || "—"}\n\n📋 История записей: ${x._count.bookings}`, kb); }
    if (action === "findclient" || action === "findpet") { await setFlow(admin.id, action); return void await render(ctx, action === "findclient" ? "🔎 Введите имя, username, телефон или Telegram ID клиента:" : "🔎 Введите имя или породу питомца:", nav(action === "findclient" ? "ad:clients" : "ad:pets")); }
    if (action === "services") { const rows = await prisma.service.findMany({ orderBy: { sortOrder: "asc" } }), kb = new InlineKeyboard().text("➕ Добавить услугу", "ad:serviceadd").row(); rows.forEach(x => kb.text(`${x.isActive && !x.isArchived ? "✂️" : "⚪"} ${x.name} · ${money(x.priceKopecks)}`, `ad:service:${x.id}`).row()); kb.text("⬅️ Назад", "ad:home"); return void await render(ctx, "✂️ УСЛУГИ", kb); }
    if (action === "service") { const x = await prisma.service.findUniqueOrThrow({ where: { id: a } }), kb = new InlineKeyboard().text("✏️ Изменить", `ad:serviceedit:${a}`).text(x.isActive ? "🔴 Выключить" : "🟢 Включить", `ad:servicetoggle:${a}`).row().text("🗑 Архивировать", `ad:servicearchive:${a}`).row().text("⬅️ Назад", "ad:services"); return void await render(ctx, `✂️ ${x.name}\n💰 ${money(x.priceKopecks)}\n⏱ ${x.durationMinutes} мин.\n${x.description || ""}\n${x.isActive && !x.isArchived ? "🟢 Активна" : "⚪ Неактивна"}`, kb); }
    if (action === "prices") { const rows = await prisma.service.findMany({ where: { isArchived: false }, orderBy: { name: "asc" } }), kb = new InlineKeyboard(); rows.forEach(x => kb.text(`${x.name} — ${money(x.priceKopecks)}`, `ad:price:${x.id}`).row()); kb.text("⬅️ Назад", "ad:home"); return void await render(ctx, "💰 ЦЕНЫ", kb); }
    if (action === "price") { await setFlow(admin.id, "price", { serviceId: a }); return void await render(ctx, "Введите новую цену в рублях, например: 4000", nav("ad:prices")); }
    if (action === "serviceedit") return void await render(ctx, "✏️ Что изменить?", new InlineKeyboard().text("Название", `ad:servicefield:${a}:name`).text("Описание", `ad:servicefield:${a}:description`).row().text("Цену", `ad:servicefield:${a}:priceKopecks`).text("Длительность", `ad:servicefield:${a}:durationMinutes`).row().text("⬅️ К услуге", `ad:service:${a}`));
    if (action === "servicefield") { await setFlow(admin.id, "serviceedit", { serviceId: a, field: b }); return void await render(ctx, b === "priceKopecks" ? "Введите новую цену в рублях:" : b === "durationMinutes" ? "Введите новую длительность в минутах:" : b === "description" ? "Введите описание или «—», чтобы очистить:" : "Введите новое название услуги:", nav(`ad:service:${a}`)); }
    if (action === "servicearchive") return void await render(ctx, "⚠️ Архивировать услугу? Она исчезнет из прайса и новых записей, а история сохранится.", new InlineKeyboard().text("✅ Архивировать", `ad:servicearchiveyes:${a}`).row().text("❌ Отмена", `ad:service:${a}`));
    if (action === "servicearchiveyes") { await prisma.service.update({ where: { id: a }, data: { isArchived: true, isActive: false } }); return void await render(ctx, "✅ Услуга архивирована. История записей сохранена.", nav("ad:services")); }
    if (action === "servicetoggle") { const x = await prisma.service.findUniqueOrThrow({ where: { id: a } }); await prisma.service.update({ where: { id: a }, data: { isActive: !x.isActive } }); return void await render(ctx, "✅ Активность услуги изменена.", nav("ad:services")); }
    if (action === "serviceadd") { const cats = await prisma.serviceCategory.findMany({ where: { isArchived: false } }); if (!cats.length) { await setFlow(admin.id, "categoryname"); return void await render(ctx, "Введите название первой категории услуг:", new InlineKeyboard().text("❌ Отмена", "ad:servicecancel")); } const kb = new InlineKeyboard(); cats.forEach(x => kb.text(x.name, `ad:servicecat:${x.id}`).row()); kb.text("❌ Отмена", "ad:servicecancel"); return void await render(ctx, "Выберите категорию:", kb); }
    if (action === "servicecat") { await setFlow(admin.id, "servicename", { categoryId: a }); return void await render(ctx, "Введите название услуги:", new InlineKeyboard().text("❌ Отмена", "ad:servicecancel")); }
    if (action === "servicepreview") { const f = await getFlow(admin.id); if (!f?.categoryId || !f.name || !f.price || !f.duration) return void await render(ctx, "Черновик услуги не найден.", nav("ad:services")); return void await render(ctx, `✂️ НОВАЯ УСЛУГА\n\nНазвание: ${f.name}\nОписание: ${f.description || "—"}\nЦена: ${money(Number(f.price))}\nДлительность: ${f.duration} мин`, new InlineKeyboard().text("✅ Создать", "ad:servicecreate").text("✏️ Изменить", "ad:serviceeditdraft").row().text("❌ Отмена", "ad:servicecancel")); }
    if (action === "serviceeditdraft") { await clearFlow(admin.id); return void await render(ctx, "Введите данные услуги заново.", new InlineKeyboard().text("➕ Начать создание", "ad:serviceadd").row().text("❌ Отмена", "ad:servicecancel")); }
    if (action === "servicecancel") { await clearFlow(admin.id); return void await render(ctx, "Создание услуги отменено.", nav("ad:services")); }
    if (action === "servicecreate") { const f = await getFlow(admin.id); if (!f?.categoryId || !f.name || !f.price || !f.duration) return void await render(ctx, "Черновик услуги не найден или уже обработан.", nav("ad:services")); const locked = await prisma.botFlow.updateMany({ where: { userId: admin.id, state: "admin:serviceconfirm" }, data: { state: "admin:servicecreating" } }); if (!locked.count) return void await render(ctx, "⚠️ Создание уже обрабатывается.", nav("ad:services")); const priceKopecks = Number(f.price), durationMinutes = Number(f.duration); if (!Number.isSafeInteger(priceKopecks) || priceKopecks < 0 || !Number.isInteger(durationMinutes) || durationMinutes < 15) { await clearFlow(admin.id); return void await render(ctx, "Данные услуги некорректны. Начните создание заново.", nav("ad:services")); } const masters = await prisma.master.findMany({ where: { isActive: true, isArchived: false }, select: { id: true } }); await prisma.service.create({ data: { categoryId: f.categoryId, name: f.name, description: f.description || null, priceKopecks, durationMinutes, animalTypes: ["dog", "cat"], masterServices: { create: masters.map(master => ({ masterId: master.id })) } } }); await clearFlow(admin.id); return void await render(ctx, "✅ Услуга создана и сразу доступна активным мастерам.", nav("ad:services")); }
    if (action === "masters") { const rows = await prisma.master.findMany({ orderBy: { name: "asc" } }), kb = new InlineKeyboard().text("➕ Добавить мастера", "ad:masteradd").row(); rows.forEach(x => kb.text(`${x.isActive && !x.isArchived ? "👩" : "⚪"} ${x.name}`, `ad:master:${x.id}`).row()); kb.text("⬅️ Назад", "ad:home"); return void await render(ctx, "👩 МАСТЕРА", kb); }
    if (action === "master") { const x = await prisma.master.findUniqueOrThrow({ where: { id: a }, include: { services: { include: { service: true } } } }), kb = new InlineKeyboard().text("✏️ Изменить", `ad:masteredit:${a}`).text(x.isActive ? "🔴 Выключить" : "🟢 Включить", `ad:mastertoggle:${a}`).row().text("🗑 Архивировать", `ad:masterarchive:${a}`).row().text("⬅️ Назад", "ad:masters"); return void await render(ctx, `👩 ${x.name}\nСтатус: ${x.isActive && !x.isArchived ? "🟢 Активен" : "⚪ Неактивен"}\nУслуги: ${x.services.map(s => s.service.name).join(", ") || "не назначены"}`, kb); }
    if (action === "masteradd" || action === "masteredit") { await setFlow(admin.id, action, action === "masteredit" ? { masterId: a } : {}); return void await render(ctx, action === "masteredit" ? "✏️ Введите новое имя мастера:" : "Введите имя мастера:", nav("ad:masters")); }
    if (action === "mastertoggle" || action === "masterarchive") { const x = await prisma.master.findUniqueOrThrow({ where: { id: a } }); await prisma.master.update({ where: { id: a }, data: action === "mastertoggle" ? { isActive: !x.isActive } : { isArchived: true, isActive: false } }); return void await render(ctx, action === "mastertoggle" ? "✅ Активность мастера изменена." : "✅ Мастер архивирован.", nav("ad:masters")); }
    if (action === "stats") { const cfg = await settings(), d = await today(), periods = [["Сегодня", d, date(d, 1)], ["За неделю", date(d, -6), date(d, 1)], ["За месяц", date(d, -29), date(d, 1)]] as const; const parts = await Promise.all(periods.map(async ([title, from, to]) => { const where = { startsAt: { gte: studioDateTime(from, 0, cfg.timezone), lt: studioDateTime(to, 0, cfg.timezone) }, status: { not: "CANCELLED" as const } }; const [n, sum] = await Promise.all([prisma.booking.count({ where }), prisma.booking.aggregate({ _sum: { priceKopecks: true }, where })]); return `${title}:\n📅 ${n} записей\n💰 ${money(sum._sum.priceKopecks || 0, cfg.currency)}`; })); const top = await prisma.booking.groupBy({ by: ["serviceId"], _count: { serviceId: true }, orderBy: { _count: { serviceId: "desc" } }, take: 3 }), names = await prisma.service.findMany({ where: { id: { in: top.map(x => x.serviceId) } }, select: { id: true, name: true } }); return void await render(ctx, `📊 СТАТИСТИКА\n\n${parts.join("\n\n")}\n\n🏆 Популярные услуги\n${top.map(x => `• ${names.find(n => n.id === x.serviceId)?.name || "Услуга"} — ${x._count.serviceId}`).join("\n") || "—"}`, nav()); }
    if (action === "broadcast") return void await render(ctx, "📢 РАССЫЛКА", new InlineKeyboard().text("📢 Создать рассылку", "ad:broadcastnew").row().text("⬅️ Назад", "ad:home"));
    if (action === "broadcastnew") { await setFlow(admin.id, "broadcast"); return void await render(ctx, "📢 РАССЫЛКА\n\nВведите сообщение для рассылки:", nav("ad:broadcast")); }
    if (action === "broadcastconfirm") { const f = await getFlow(admin.id); if (!f?.text) return void await render(ctx, "Черновик рассылки не найден.", nav("ad:broadcast")); return void await render(ctx, "⚠️ Отправить сообщение всем незаблокированным клиентам?", new InlineKeyboard().text("✅ Да, отправить", "ad:broadcastsend").row().text("❌ Отмена", "ad:broadcastcancel")); }
    if (action === "broadcastsend") { const f = await getFlow(admin.id); if (!f?.text) return void await render(ctx, "Черновик рассылки не найден.", nav("ad:broadcast")); const users = await prisma.user.findMany({ where: { isBlocked: false }, select: { telegramId: true } }); let sent = 0, failed = 0; for (const x of users) try { await bot.api.sendMessage(x.telegramId.toString(), f.text); sent++; } catch { failed++; } await clearFlow(admin.id); return void await render(ctx, `📢 Рассылка завершена.\n\nОтправлено: ${sent}\nОшибок: ${failed}`, nav("ad:broadcast")); }
    if (action === "broadcastcancel") { await clearFlow(admin.id); return void await render(ctx, "Рассылка отменена.", nav("ad:broadcast")); }
    if (action === "settings") return void await render(ctx, "⚙️ НАСТРОЙКИ", new InlineKeyboard().text("Название", "ad:set:name").text("Адрес", "ad:set:address").row().text("Телефон", "ad:set:phone").text("Часовой пояс", "ad:set:timezone").row().text("Приветствие", "ad:set:welcomeText").text("Текст после записи", "ad:set:bookingSuccessText").row().text("⬅️ Назад", "ad:home"));
    if (action === "set") { await setFlow(admin.id, "setting", { field: a }); return void await render(ctx, `Введите новое значение для «${a}»:`, nav("ad:settings")); }
    if (action === "schedule") return void await scheduleOverview(ctx, await today());
    if (action === "schedulepick") return void await dates(ctx, "ad:scheduledate", "ad:schedule");
    if (action === "scheduledate") return void await scheduleOverview(ctx, a);
    if (action === "sch") return void await dates(ctx, `ad:schdate:${a}`, "ad:schedule");
    if (action === "schdate") return void await scheduleDay(ctx, a, b);
    if (action === "schbookings") { const cfg = await settings(), start = studioDateTime(b, 0, cfg.timezone), end = studioDateTime(date(b, 1), 0, cfg.timezone), rows = await prisma.booking.findMany({ where: { masterId: a, startsAt: { gte: start, lt: end } }, include: { pet: true, service: true }, orderBy: { startsAt: "asc" } }); return void await render(ctx, rows.length ? `📋 ЗАПИСИ · ${dayLabel(b)}\n\n${rows.map(x => `${x.startsAt.toLocaleTimeString("ru-RU", { timeZone: cfg.timezone, hour: "2-digit", minute: "2-digit" })} · ${x.pet.name} · ${x.service.name}\n${label(x.status)}`).join("\n\n")}` : "📋 На этот день записей нет.", nav(`ad:schdate:${a}:${b}`)); }
    if (action === "blocks") { const cfg = await settings(), from = studioDateTime(await today(), 0, cfg.timezone), rows = await prisma.blockedTime.findMany({ where: { endsAt: { gte: from } }, include: { master: true }, orderBy: { startsAt: "asc" }, take: 30 }), kb = new InlineKeyboard().text("➕ Заблокировать окно", "ad:blockpick").row(); rows.forEach(x => kb.text(`🗑 ${x.startsAt.toLocaleDateString("ru-RU", { timeZone: cfg.timezone })} ${x.startsAt.toLocaleTimeString("ru-RU", { timeZone: cfg.timezone, hour: "2-digit", minute: "2-digit" })} · ${x.master.name}`, `ad:unblock:${x.id}`).row()); kb.text("⬅️ Назад", "ad:home"); return void await render(ctx, rows.length ? "🚫 ЗАБЛОКИРОВАННЫЕ ОКНА\n\nНажмите окно, чтобы разблокировать:" : "🚫 ЗАБЛОКИРОВАННЫЕ ОКНА\n\nАктивных блокировок нет.", kb); }
    if (action === "blockpick") return void await masters(ctx, "ad:blockmaster", "ad:blocks");
    if (action === "blockmaster") return void await dates(ctx, `ad:blockdate:${a}`, "ad:blocks");
    if (action === "blockdate") { await setFlow(admin.id, "block", { masterId: a, date: b }); return void await render(ctx, "Введите период блокировки в формате 09:00-10:00:", nav("ad:blocks")); }
    if (action === "unblock") { await prisma.blockedTime.delete({ where: { id: a } }); return void await render(ctx, "✅ Блокировка снята.", nav("ad:blocks")); }
    if (["addwin", "block", "day"].includes(action)) { await setFlow(admin.id, action, { masterId: a, date: b }); return void await render(ctx, action === "addwin" ? "Введите время окна в формате 09:00-10:00:" : action === "day" ? "Введите часы дня 09:00-18:00 или «выходной»." : "Введите период блокировки в формате 09:00-10:00:", nav("ad:schedule")); }
    if (action === "newbooking") { const rows = await prisma.user.findMany({ take: 20, orderBy: { createdAt: "desc" } }), kb = new InlineKeyboard(); rows.forEach(x => kb.text(`👤 ${x.firstName || x.username || x.telegramId}`, `ad:newclient:${x.id}`).row()); kb.text("⬅️ Назад", "ad:home"); return void await render(ctx, "➕ СОЗДАТЬ ЗАПИСЬ\n\nВыберите клиента:", kb); }
    if (action === "newclient") { const rows = await prisma.pet.findMany({ where: { ownerId: a, isArchived: false } }), kb = new InlineKeyboard(); rows.forEach(x => kb.text(`${icon(x.species)} ${x.name}`, `ad:newpet:${x.id}`).row()); kb.text("⬅️ Назад", "ad:newbooking"); return void await render(ctx, "Выберите питомца:", kb); }
    if (action === "newpet") { const pet = await prisma.pet.findUniqueOrThrow({ where: { id: a } }), rows = await prisma.service.findMany({ where: { isActive: true, isArchived: false, animalTypes: { has: pet.species } } }), kb = new InlineKeyboard(); rows.forEach(x => kb.text(`${x.name} — ${money(x.priceKopecks)}`, `ad:newservice:${pet.id}:${x.id}`).row()); return void await render(ctx, "Выберите услугу:", kb); }
    if (action === "newservice") { const rows = await prisma.master.findMany({ where: { isActive: true, isArchived: false, services: { some: { serviceId: b } } } }), kb = new InlineKeyboard(); rows.forEach(x => kb.text(`👩 ${x.name}`, `ad:newmaster:${a}:${b}:${x.id}`).row()); return void await render(ctx, "Выберите мастера:", kb); }
    if (action === "newmaster") { await setFlow(admin.id, "newdate", { petId: a, serviceId: b, masterId: c }); return void await dates(ctx, "ad:newdatepick", "ad:newbooking"); }
    if (action === "newdatepick") { const f = await getFlow(admin.id); if (!f) return; const slots = await availableSlots(f.masterId, f.serviceId, a), kb = new InlineKeyboard(); slots.forEach((x, i) => { kb.text(clock(x.minutes), `ad:newtime:${x.minutes}`); if (i % 4 === 3) kb.row(); }); await setFlow(admin.id, "newtime", { ...f, date: a }); return void await render(ctx, slots.length ? "Выберите время:" : "Нет доступного времени.", kb); }
    if (action === "newtime") { const f = await getFlow(admin.id); if (!f) return; try { const cfg = await settings(), pet = await prisma.pet.findUniqueOrThrow({ where: { id: f.petId } }), booking = await createBooking({ clientId: pet.ownerId, petId: f.petId, serviceId: f.serviceId, masterId: f.masterId, startsAt: studioDateTime(f.date, Number(a), cfg.timezone) }); await clearFlow(admin.id); return void await render(ctx, `✅ Запись создана: ${booking.pet.name}, ${f.date} ${clock(Number(a))}.`, nav("ad:bookings")); } catch (e) { return void await render(ctx, e instanceof SlotTakenError ? "❌ Слот уже занят." : "Не удалось создать запись.", nav("ad:newbooking")); } }
  });
  bot.on("message:text", async (ctx, next) => {
    if (!isOwner(ctx)) return next(); const admin = await actor(ctx), f = await getFlow(admin.id); if (!f) return next(); const state = (await prisma.botFlow.findUniqueOrThrow({ where: { userId: admin.id } })).state.slice(6), text = ctx.message.text.trim();
    if (state === "clientmessage") { await setFlow(admin.id, "clientmessageconfirm", { ...f, text }); return void await ctx.reply(`📨 Сообщение:\n\n${text}`, { reply_markup: new InlineKeyboard().text("📤 Отправить", "ad:clientmessagesend").text("❌ Отмена", `ad:client:${f.clientId}`) }); }
    if (state === "broadcast") { await setFlow(admin.id, "broadcastconfirm", { text }); return void await ctx.reply(`📢 ПРЕДПРОСМОТР\n\n${text}`, { reply_markup: new InlineKeyboard().text("📤 Отправить всем", "ad:broadcastconfirm").row().text("❌ Отмена", "ad:broadcastcancel") }); }
    if (state === "clientedit" || state === "petedit") { if (state === "clientedit") await prisma.user.update({ where: { id: f.clientId }, data: { firstName: text } }); else await prisma.pet.update({ where: { id: f.petId }, data: { name: text } }); await clearFlow(admin.id); return void await ctx.reply("✅ Данные сохранены.", { reply_markup: nav(state === "clientedit" ? `ad:client:${f.clientId}` : `ad:pet:${f.petId}`) }); }
    if (state === "findclient") { const digits = text.replace(/\D/g, ""), ids = digits && digits.length <= 19 ? [{ telegramId: BigInt(digits) }] : [], rows = await prisma.user.findMany({ where: { OR: [{ firstName: { contains: text, mode: "insensitive" } }, { username: { contains: text.replace(/^@/, ""), mode: "insensitive" } }, { phone: { contains: text, mode: "insensitive" } }, ...ids] }, take: 20 }), kb = new InlineKeyboard(); rows.forEach(x => kb.text(`👤 ${x.firstName || x.username || x.telegramId}`, `ad:client:${x.id}`).row()); kb.text("⬅️ К клиентам", "ad:clients"); await clearFlow(admin.id); return void await ctx.reply(rows.length ? "🔎 Результаты поиска:" : "🔎 Клиент не найден.", { reply_markup: kb }); }
    if (state === "findpet") { const rows = await prisma.pet.findMany({ where: { isArchived: false, OR: [{ name: { contains: text, mode: "insensitive" } }, { breed: { contains: text, mode: "insensitive" } }] }, include: { owner: true }, take: 20 }), kb = new InlineKeyboard(); rows.forEach(x => kb.text(`${icon(x.species)} ${x.name} · ${x.owner.firstName || "владелец"}`, `ad:pet:${x.id}`).row()); kb.text("⬅️ К питомцам", "ad:pets"); await clearFlow(admin.id); return void await ctx.reply(rows.length ? "🔎 Результаты поиска:" : "🔎 Питомец не найден.", { reply_markup: kb }); }
    if (state === "masteradd" || state === "masteredit") { if (state === "masteradd") { const services = await prisma.service.findMany({ where: { isActive: true, isArchived: false }, select: { id: true } }); await prisma.master.create({ data: { name: text, services: { create: services.map(x => ({ serviceId: x.id })) } } }); } else await prisma.master.update({ where: { id: f.masterId }, data: { name: text } }); await clearFlow(admin.id); return void await ctx.reply("✅ Мастер сохранён.", { reply_markup: nav("ad:masters") }); }
    if (state === "categoryname" || state === "categoryadd") { if (!text) return void await ctx.reply("Название категории не может быть пустым."); const category = await prisma.serviceCategory.findFirst({ where: { name: { equals: text, mode: "insensitive" }, isArchived: false } }); if (category) await setFlow(admin.id, "servicename", { categoryId: category.id }); else { const x = await prisma.serviceCategory.create({ data: { name: text } }); await setFlow(admin.id, "servicename", { categoryId: x.id }); } return void await ctx.reply("Введите название услуги:", { reply_markup: new InlineKeyboard().text("❌ Отмена", "ad:servicecancel") }); }
    if (state === "servicename") { if (!text) return void await ctx.reply("Название услуги не может быть пустым. Введите название ещё раз."); await setFlow(admin.id, "servicedescription", { ...f, name: text }); return void await ctx.reply("Введите описание услуги или «—», чтобы пропустить:", { reply_markup: new InlineKeyboard().text("❌ Отмена", "ad:servicecancel") }); }
    if (state === "servicedescription") { if (!text) return void await ctx.reply("Введите описание или «—», чтобы пропустить."); await setFlow(admin.id, "serviceprice", { ...f, description: text === "—" ? "" : text }); return void await ctx.reply("Введите цену в рублях:", { reply_markup: new InlineKeyboard().text("❌ Отмена", "ad:servicecancel") }); }
    if (state === "serviceprice") { const n = Number(text.replace(",", ".")); if (!Number.isFinite(n) || n < 0 || !Number.isSafeInteger(Math.round(n * 100))) return void await ctx.reply("Введите корректную цену числом, например 2500."); await setFlow(admin.id, "serviceduration", { ...f, price: String(Math.round(n * 100)) }); return void await ctx.reply("Введите длительность в минутах, например 120:", { reply_markup: new InlineKeyboard().text("❌ Отмена", "ad:servicecancel") }); }
    if (state === "serviceduration") { const n = Number(text); if (!Number.isInteger(n) || n < 15) return void await ctx.reply("Введите длительность целым числом не менее 15 минут."); await setFlow(admin.id, "serviceconfirm", { ...f, duration: String(n) }); return void await ctx.reply(`✂️ НОВАЯ УСЛУГА\n\nНазвание: ${f.name}\nОписание: ${f.description || "—"}\nЦена: ${money(Number(f.price))}\nДлительность: ${n} мин`, { reply_markup: new InlineKeyboard().text("✅ Создать", "ad:servicecreate").text("✏️ Изменить", "ad:serviceeditdraft").row().text("❌ Отмена", "ad:servicecancel") }); }
    if (state === "serviceedit") { if (f.field === "name") { if (!text) return void await ctx.reply("Название не может быть пустым."); await prisma.service.update({ where: { id: f.serviceId }, data: { name: text } }); } else if (f.field === "description") await prisma.service.update({ where: { id: f.serviceId }, data: { description: text === "—" ? null : text } }); else if (f.field === "priceKopecks") { const n = Number(text.replace(",", ".")); if (!Number.isFinite(n) || n < 0) return void await ctx.reply("Введите корректную цену."); await prisma.service.update({ where: { id: f.serviceId }, data: { priceKopecks: Math.round(n * 100) } }); } else if (f.field === "durationMinutes") { const n = Number(text); if (!Number.isInteger(n) || n < 15) return void await ctx.reply("Введите длительность не менее 15 минут."); await prisma.service.update({ where: { id: f.serviceId }, data: { durationMinutes: n } }); } else return next(); await clearFlow(admin.id); return void await ctx.reply("✅ Услуга обновлена.", { reply_markup: nav(`ad:service:${f.serviceId}`) }); }
    if (state === "price") { const n = Number(text.replace(",", ".")); if (!Number.isFinite(n) || n < 0) return void await ctx.reply("Введите корректную цену."); await prisma.service.update({ where: { id: f.serviceId }, data: { priceKopecks: Math.round(n * 100) } }); await clearFlow(admin.id); return void await ctx.reply("✅ Цена обновлена.", { reply_markup: nav("ad:prices") }); }
    if (state === "setting") { const fields = ["name", "address", "phone", "timezone", "welcomeText", "bookingSuccessText"]; if (!fields.includes(f.field)) return next(); await prisma.studioSettings.update({ where: { id: 1 }, data: { [f.field]: text } }); await clearFlow(admin.id); return void await ctx.reply("✅ Настройка сохранена.", { reply_markup: nav("ad:settings") }); }
    if (["day", "addwin", "block"].includes(state)) { const cfg = await settings(); if (state === "day" && text.toLowerCase() === "выходной") { await prisma.scheduleException.upsert({ where: { masterId_date: { masterId: f.masterId, date: new Date(`${f.date}T00:00:00.000Z`) } }, update: { isDayOff: true, startMinutes: null, endMinutes: null }, create: { masterId: f.masterId, date: new Date(`${f.date}T00:00:00.000Z`), isDayOff: true } }); await clearFlow(admin.id); return void await ctx.reply("✅ День сделан выходным."); } const m = /^(\d{1,2}):(\d{2})-(\d{1,2}):(\d{2})$/.exec(text); if (!m) return void await ctx.reply("Формат: 09:00-18:00"); const start = Number(m[1]) * 60 + Number(m[2]), end = Number(m[3]) * 60 + Number(m[4]); if (start < 0 || end > 1440 || end <= start) return void await ctx.reply("Укажите корректный период."); const startsAt = studioDateTime(f.date, start, cfg.timezone), endsAt = studioDateTime(f.date, end, cfg.timezone); if (state === "day") await prisma.scheduleException.upsert({ where: { masterId_date: { masterId: f.masterId, date: new Date(`${f.date}T00:00:00.000Z`) } }, update: { isDayOff: false, startMinutes: start, endMinutes: end }, create: { masterId: f.masterId, date: new Date(`${f.date}T00:00:00.000Z`), isDayOff: false, startMinutes: start, endMinutes: end } }); else if (state === "addwin") await prisma.availabilityWindow.create({ data: { masterId: f.masterId, startsAt, endsAt } }); else { const existing = await prisma.booking.findFirst({ where: { masterId: f.masterId, status: { in: [...ACTIVE] }, startsAt: { lt: endsAt }, endsAt: { gt: startsAt } } }); if (existing) return void await ctx.reply("⚠️ На это время уже есть запись."); await prisma.blockedTime.create({ data: { masterId: f.masterId, startsAt, endsAt } }); } await clearFlow(admin.id); return void await ctx.reply(state === "addwin" ? "✅ Окно добавлено." : state === "block" ? "✅ Время заблокировано." : "✅ Часы дня сохранены."); }
    return next();
  });
}
